# Power iteration

In mathematics, power iteration (also known as the power method) is an eigenvalue algorithm: given a diagonalizable matrix $A$, the algorithm will produce a number $\lambda$, which is the greatest (in absolute value) eigenvalue of $A$, and a nonzero vector $v$, which is a corresponding eigenvector of $\lambda$ , that is, $Av=\lambda v$.

https://en.wikipedia.org/wiki/Power_iteration

In [58]:
import numpy as np

def power_iteration(A, num_simulations: int):
    # Ideally choose a random vector
    # To decrease the chance that our vector
    # Is orthogonal to the eigenvector
    b_k = np.random.rand(A.shape[1])

    for _ in range(num_simulations):
        # calculate the matrix-by-vector product Ab
        b_k1 = np.dot(A, b_k)

        # calculate the norm
        b_k1_norm = np.linalg.norm(b_k1)

        # re normalize the vector
        b_k = b_k1 / b_k1_norm

    return b_k

In [81]:
A = np.array([[0.5, 0.5, 0.3], [0.2, 0.8, 0.2], [0.1, 0.2, 0.3]])
num_simulations = 1000

In [82]:
power_iteration(A, num_simulations)

array([0.69933688, 0.66654719, 0.25815262])

In [83]:
eigvals, eigvecs = np.linalg.eig(A)

In [84]:
eigvals 

array([1.08729833, 0.31270167, 0.2       ])

In [87]:
eigvecs[:,np.argmax(eigvals)]

array([-0.69933688, -0.66654719, -0.25815262])